
# url for ARCH home page
url_home: "app.parse-health.org/ARCH/"

# url for phecodemap
url_phe: "https://celehs.connect.hms.harvard.edu/phecodemap/?phecode="

# database
db:
    dbname: "app_cuinetwork"
    host: celehs-db-instance.ctkwpvy5lvqg.us-east-1.rds.amazonaws.com
    port: 5432
    user: postgres
    password: Ubwvu2HXYqRneFIR4dkr




