
# url for ARCH home page
url_home: https://app.parse-health.org/ARCH/

# url for phecodemap
url_phe: https://phenomics.va.ornl.gov/phecodemap/

# (Optional) linkage csv file
uqid_mapping: demo_uqid_mapping.csv

# database
db:
    dbname: app_cuinetwork
    host: celehs-db-instance.ctkwpvy5lvqg.us-east-1.rds.amazonaws.com
    port: 5432
    user: postgres
    password: Ubwvu2HXYqRneFIR4dkr




